# $Id$

if(EXISTS ${CMAKE_SOURCE_DIR}/.install AND CMAKE_CROSSCOMPILING)
	execute_process(
		COMMAND readlink "${CMAKE_SOURCE_DIR}/.install"
		OUTPUT_VARIABLE CMAKE_INSTALL_PREFIX
		ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE
	)
	message( "-- Install to: ${CMAKE_INSTALL_PREFIX}" )
	add_custom_command(
		TARGET ${PROJECT_NAME} POST_BUILD
		COMMAND +${CMAKE_COMMAND} --build ${CMAKE_BINARY_DIR} --target install
	)
	install(
		PROGRAMS ${PROJECT_BINARY_DIR}/${PROJECT_NAME_BIN}
		DESTINATION ${CMAKE_INSTALL_PREFIX}
	)
endif()
